# Generated by Django 3.0.5 on 2021-01-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='writer',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='isArchive',
        ),
    ]
