# Generated by Django 3.1.5 on 2021-01-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_notes_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
